name: Contributor License Agreement (CLA)

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  cla:
    runs-on: ubuntu-latest
    if: |
      (github.event.issue.pull_request 
        && !github.event.issue.pull_request.merged_at
        && contains(github.event.comment.body, 'signed')
      ) 
      || (github.event.pull_request && !github.event.pull_request.merged)
    steps:
      - name: Set CLA Token Fallback
        id: cla_token
        run: |
          if [ -z "${{ secrets.CLA_TOKEN }}" ]; then
            echo "token=dummy_token" >> $GITHUB_OUTPUT
          else
            echo "token=${{ secrets.CLA_TOKEN }}" >> $GITHUB_OUTPUT
          fi
      - uses: Shopify/shopify-cla-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cla-token: ${{ steps.cla_token.outputs.token }}
